version: '3.8'

services:
  app1:
    build: .
    environment:
      - app_name=app1
    ports:
      - "8001:8000"

  app2:
    build: .
    environment:
      - app_name=app2
    ports:
      - "8002:8000"

  app3:
    build: .
    environment:
      - app_name=app3
    ports:
      - "8003:8000"

  nginx:
    image: nginx:alpine
    ports:
      - "8081:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3